#!/bin/sh /etc/rc.common

START=66

NAME=commotion-service-manager
EXEC=/usr/sbin/${NAME}
SCHEMA_DIR=/etc/commotion/csm/schemas.d/
PID_DIR=/var/run
SERVICE_PID_FILE=${PID_DIR}/${NAME}.pid
DAEMON_ARGS="-u -p $SERVICE_PID_FILE -s $SCHEMA_DIR"

boot() {
  mkdir -m 0755 -p $PID_DIR $SCHEMA_DIR
  start
}

start() {
  service_start $EXEC $DAEMON_ARGS
}

stop() {
  service_stop $EXEC
}