#!/bin/sh /etc/rc.common

START=66

NAME=commotion-service-manager
EXEC=/usr/sbin/${NAME}
OUTPUT_FILE=/tmp/local-services.out
PID_DIR=/var/run
SERVICE_PID_FILE=${PID_DIR}/${NAME}.pid
DAEMON_ARGS="-u -o $OUTPUT_FILE -p $SERVICE_PID_FILE"

boot() {
  mkdir -m 0755 -p $PID_DIR
  start
}

start() {
  service_start $EXEC $DAEMON_ARGS
}

stop() {
  service_stop $EXEC
}